//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TvRecorderFinall
{
    using System;
    using System.Collections.Generic;
    
    public partial class Record
    {
        public int ID { get; set; }
        public int IdNotification { get; set; }
        public int SAP { get; set; }
        public System.DateTime Date { get; set; }
        public string Login { get; set; }
        public string FileName { get; set; }
    }
}
